language: ruby
rvm:
- 2.5.0
env:
  global:
  - SPHINX_BIN=ext/sphinx/bin/
  - secure: aP3wCZnnqim/yBWbO8+N2DAJIDVuqewUayK3nBphR/Jt1POIMbqCIuHwk/SG/JfMc6pJIlH0QOX8wI3fF3y5GO6aIrN8xKAX0DoDm+Gkvk/YEk3cK/2fJUwvocR89M99EoV8ctLPaR03B3dm3h2Dh2oe8NQRBfcrL3WtiHHq3d0=
  matrix:
  - SPHINX_VERSION=3.0.2
before_script:
- killall searchd; echo ''
- "./bin/loadsphinx $SPHINX_VERSION"
before_install:
- gem update --system
after_script:
- killall searchd; echo ''
sudo: false
